export const Data =[
    {
        id: 1,
        business: 'Disney',
        date: '02/03/2021',
        amount: '110.25',
        status: 'Pending',
    },
    {
        id: 2,
        business: 'Spectrum',
        date: '02/01/2021',
        amount: '63.68',
        status: 'Pending',
    },
    {
        id: 3,
        business: 'verizon',
        date: '02/03/2021',
        amount: '1000',
        status: 'Pending',
    },
    {
        id: 4,
        business: 'Devendra Traders',
        date: '02/03/2021',
        amount: '1000',
        status: 'Pending',
    },
    {
        id: 5,
        business: 'Mahira Fruits',
        date: '02/03/2021',
        amount: '1000',
        status: 'Pending',
    },
    {
        id: 6,
        business: 'Sugadpal Yadav Agriculture Farm',
        date: '02/03/2021',
        amount: '110.25',
        status: 'Past Due',
    },
    {
        id: 7,
        business: 'Santosh Agri Trading',
        date: '02/05/2021',
        amount: '63.68',
        status: 'Past Due',
    },
    {
        id: 8,
        business: 'Y.S. Raghuvanshi Krishi Farm',
        date: '02/05/2021',
        amount: '63.68',
        status: 'Past Due',
    },
    {
        id: 9,
        business: 'Jadhav Fruit & Vegetables',
        date: '02/03/2021',
        amount: '63.68',
        status: 'Past Due',
    },
    {
        id: 10,
        business: 'VIP Import Export',
        date: '02/03/2021',
        amount: '63.68',
        status: 'Past Due',
    },
    {
        id: 11,
        business: 'True Value',
        date: '02/03/2021',
        amount: '63.68',
        status: 'Past Due',
    },
    {
        id: 12,
        business: 'Orgill',
        date: '02/03/2021',
        amount: '17.07',
        status: 'Paid',
    },
    {
        id: 13,
        business: 'Rohit Singh & Traders',
        date: '02/03/2021',
        amount: '17.07',
        status: 'Paid',
    },
    {
        id: 14,
        business: 'Krishi Achariya Traders',
        date: '02/03/2021',
        amount: '17.07',
        status: 'Paid',
    },
    {
        id: 15,
        business: 'Fruit and Vegetable Supplyres',
        date: '02/01/2021',
        amount: '17.07',
        status: 'Paid',
    },
    {
        id: 16,
        business: 'Sidhrath Yadav & Sons',
        date: '02/01/2021',
        amount: '17.07',
        status: 'Paid',
    },
    {
        id: 17,
        business: 'Chandravanshi Trading',
        date: '02/01/2021',
        amount: '17.07',
        status: 'Paid',
    },
    {
        id: 18,
        business: 'RNS Products',
        date: '02/03/2021',
        amount: '63.68',
        status: 'Past Due',
    },
    {
        id: 19,
        business: 'GP Kart',
        date: '02/03/2021',
        amount: '63.68',
        status: 'Past Due',
    },
    {
        id: 20,
        business: 'Raeesh Krishi Vyapaar',
        date: '02/03/2021',
        amount: '63.68',
        status: 'Past Due',
    }
]
